# -*- coding: utf-8 -*-
"""init.py_files_backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuDZe7qCrEMauOWoxVvizyQWAqg6_CCK
"""

from .House_system import app